; (function ($n2) {
	$n2.l10n.addLocalizedStrings("fr", {
		"All Group Tags": "Tous les tags de groupe"
		, "All Selected": "Tous sélectionnés"
		, "Available Choices": "Choix disponibles"
		, "Caption": "Description"
		, "Choices": "Choix"
		, "Cinemap": "Cinémappe"
		, "Couche Approuvée": "Couche Approuvée"
		, "Couche Publique": "Couche Publique"
		, "Credit": "Crédit"
		, "Edit Account": "Modifier le compte d'utilisateur"
		, "English": "Anglais"
		, "File Upload": "Téléchargement de fichier"
		, "French": "Français"
		, "Home Page": "Page d'accueil"
		, "Limit": "Limite"
		, "Linked Media Document": "Document média lié"
		, "Logs ": "Journaux d'exécution"
		, "Media (": "Média ("
		, "Média": "Média"
		, "Place": "Lieu"
		, "Record Audio": "Enregistrer audio"
		, "Record Video": "Enregistrer vidéo"
		, "Reset password?": "Réinitialiser le mot de passe ?"
		, "Search Results": "Résultats de recherche"
		, "Select a Document": "Sélectionner un document"
		, "Select a Hover Sound": "Sélectionner un son de survol"
		, "Select a Media": "Sélectionner un média"
		, "Select a Related Audio File": "Sélectionner un fichier audio lié"
		, "Select a Related Image": "Sélectionner une image liée"
		, "Select a Related Video File": "Sélectionner un fichier vidéo lié"
		, "Status": "Statut"
		, "Submissions ": "Soumissions"
		, "Subtitle": "Sous-titres"
		, "Tools": "Outils"
		, "Upload Type": "Type de téléchargement"
		, "User Search": "Recherche d'utilisateurs"
		, "home_administrator": "home_administrateur"
		, "home_layer_approved": "home_couche_approuvée"
		, "home_vetter": "home_vérificateur"
		, "model": "modèle"
		, "rwanda_administrator": "rwanda_administrateur"
		, "widget.annotationEditor.contextMenu.timeLink": "Annotations"
		, "widget.annotationEditor.contextMenu.mapThemes": "Thèmes"
		, "widget.annotationEditor.contextMenu.settings": "Paramètres"
		, "The selected document is not an image.": "Le document sélectionné n'est pas une image."
		, "Select Related Image": "Sélectionner l'image associée"
		, "Remove Related Image": "Supprimer l'image associée"
		, "No related image.": "Pas d'image associée."
		, "Image Caption": "Légende de l'image"
		, "module.multiStories.introduction.content": "Pour voir où les récits se croisent sur la carte, il faut d'abord sélectionner un thème dans le menu déroulant (ci-dessus), puis sélectionner les récits qui nous intéressent dans la légende (en bas à gauche). On peut alors cliquer sur chaque anneau cartographique pour écouter les différents récits."
		, "global.resolution.warning.dialog.title": "Les mobiles et basses résolutions ne sont pas supportées"
		, "global.resolution.warning.dialog.textContent": "Atlascine est destiné à être utilisé sur un ordinateur avec une résolution appropriée."
		, "Background": "Fond de carte"
		, "Rings": "Cernes"
		, "Solid Links": "Lignes continues"
		, "Dotted Links": "Lignes pointillées"
		, "Auto-recenter map": "Automatiquement recentrer la carte"
		, "Pan and zoom map to tagged places (takes zoomScale value into consideration)": "Activer le panoramique et le zoom automatisé (prenant le variable zoomScale en considération)"
		, "Animate": "Animer"
		, "Animate pan and zoom action": "Animer le panoramique et le zoom"
		, "Display images": "Afficher les images"
		, "Display image attachment pane when tagged text contains image attachment": "Afficher le volet d'image lorsqu'une image est jointe à un segment de texte"
		, "Zoom threshold": "Seuil de zoom"
		, "Map symbols associated with a given place disappear when zoom level is above the place's zoomScale value": "Les symboles cartographiques disparaissent quand le niveau de zoom dépasse"
		, "Cluster symbols": "Regrouper les géométries"
		, "Aggregate rings and links when zoomed out": "Agréger les cernes et les lignes lors d'un zoom en arrière"
		, "Settings": "Paramètres"
		, "Aggregation": "Agrégation"
		, "Delete": "Supprimer"
		, "Color": "Couleur"
		, "Notes": "Notes"
		, "Theme Tags": "Mots-clés"
		, "Place (": "Lieu ("
		, "Place Tags": "Lieux"
		, "Start: ": "Début"
		, "End: ": "Fin"
		, "widget.annotationEditor.mapThemeName": "Thème"
		, "widget.annotationEditor.mapThemeAssociatedTags": "Mots-clés associés"
		, "widget.annotationEditor.mapThemeAddNewTheme": "Nouveau thème"
		, "widget.annotationEditor.mapThemeTagBoxPlaceholder": "Appuyez sur Entrée pour enregistrer la balise"
		, "widget.annotationEditor.timeLinkTagBoxPlaceholder": "Appuyez sur Entrée pour enregistrer la balise"
		, "Add Image": "Ajouter une image"
		, "Remove Image": "Enlever l'image"
		, "Global Scale Factor": "Épaisseur des cernes"
		, "global.scale.factor.tooltip": "Multiplier la grandeur des cernes par la valeur définie"
		, "Global Time Offset": "La durée (en secondes) de l'animation des cernes"
		, "global.time.offset.tooltip": "La durée (en secondes) de l'animation de la croissance des cernes"
		, "Default Place Zoom Level": "Échelle de zoom par défaut"
		, "global.default.place.zoom.level.tooltip": "Le niveau de zoom par défaut qui sera atteint lorsque le zoom automatique est activé dans l'absence d'une valeur zoomScale"
		, "Initial Map View*": "Position initiale de la carte*"
		, 'The order of this bounding box is bottom left (x, y) and top right (x, y).\nUse a value of "0" if the cinemap should not have a default view.': "L'ordre de cette boîte englobante est en bas à gauche (x,y) et en haut à droite (x,y).\nMettre la valeur '0' pour ne pas imposer de position initiale à la carte."
		, "Get Current Map View": "Sauvegarder l'étendue actuelle de la carte"
		, "View All Annotations": "Afficher toutes les annotations"
		, "Annotations": "Annotations"
		, "Export Cinemap as GeoJSON": "Exporter en format GeoJSON"
		, "No notes added.": "Aucune note à afficher"
		, "widget.annotationEditor.settingsViewAllTimelinksNoAnnotationsText": "Aucune annotation à afficher"
		, "WKT Geometry": "Géométrie WKT"
		, "Zoom Scale": "Niveau de zoom"
		, "Made with ": "Fait avec "
		, " using ": " et "
		, "Atlascine": "Atlascine"
		, "gazetteer.dialog.title": "Chercher un nom de lieu"
		, "mapAndControls.feature.addOrEdit.label": "Ajouter un lieu"
		, "mapAndControls.feature.cancelEdit.label": "Annuler"
		, "gazetteer.dialog.subtitle.part1": "Chercher un lieu dans le "
		, "gazetteer.dialog.subtitle.urlText": "répertoire géographique Geonames"
		, "gazetteer.dialog.subtitle.part2": " pour saisir ses coordonnées."
		, "css.dialog.theme_selector.title": "Choisir un style"
		, "css.theme.legacy": "Classique"
		, "css.theme.dark": "Foncé"
		, "css.theme.light": "Éclairé"
		, "All Themes": "Tous les thèmes"
		, "donut.legend.timeline.logic.label": "Sélection inclusive"
		, "widget.annotationeditor.grouptag.invalid.name": "Les thèmes ne peuvent pas être vides."
		, "widget.annotationeditor.grouptag.invalid.colour": "Un code de couleur n'est pas valide."
		, "widget.annotationeditor.grouptag.missing.tags": "Un thème doit avoir au moins un mot-clé associé."
		, "widget.annotationeditor.grouptag.unmodified": "Aucune modification n'a été apportée."
		, "upload.submitForm.progress.text": "Ne fermez pas cette page avant que le téléchargement ne soit terminé."
		, "upload.buildForm.progress.text": "Ne fermez pas cette page avant que le téléchargement ne soit terminé."
	});
})(nunaliit2);
