;(function($n2){
	$n2.l10n.addLocalizedStrings("fr",{
		"All Group Tags":"Tous les tags de groupe"
		,"All Selected":"Tous sélectionnés"
		,"Available Choices":"Choix disponibles"
		,"Caption":"Description"
		,"Choices":"Choix"
		,"Cinemap":"Cinémappe"
		,"Couche Approuvée":"Couche Approuvée"
		,"Couche Publique":"Couche Publique"
		,"Credit":"Crédit"
		,"Edit Account":"Modifier le compte d'utilisateur"
		,"English":"Anglais"
		,"File Upload":"Téléchargement de fichier"
		,"French":"Français"
		,"Home Page":"Page d'accueil"
		,"Limit":"Limite"
		,"Linked Media Document":"Document média lié"
		,"Logs ":"Journaux d'exécution"
		,"Media (":"Média ("
		,"Média":"Média"
		,"Place":"Lieu"
		,"Record Audio":"Enregistrer audio"
		,"Record Video":"Enregistrer vidéo"
		,"Reset password?":"réinitialiser le mot de passe ?"
		,"Search Results":"Résultats de recherche"
		,"Select a Document":"Sélectionner un document"
		,"Select a Hover Sound":"Sélectionner un son de survol"
		,"Select a Media":"Sélectionner un média"
		,"Select a Related Audio File":"Sélectionner un fichier audio lié"
		,"Select a Related Image":"Sélectionner une image liée"
		,"Select a Related Video File":"Sélectionner un fichier vidéo lié"
		,"Status":"Statut"
		,"Submissions ":"Soumissions"
		,"Subtitle":"Sous-titres"
		,"Tools":"Outils"
		,"Upload Type":"Type de téléchargement"
		,"User Search":"Recherche d'utilisateurs"
		,"home_administrator":"home_administrateur"
		,"home_layer_approved":"home_couche_approuvée"
		,"home_vetter":"home_vérificateur"
		,"model":"modèle"
		,"rwanda_administrator":"rwanda_administrateur"
	});
})(nunaliit2);
