;(function($n2){
	$n2.l10n.addLocalizedStrings("en",{
		"module.multiStories.introduction.content": "To see where the stories intersect on the map, first select a theme from the drop-down menu (above), then select the stories of interest in the legend (bottom left). You can then click on each map ring to listen to the different stories."
		, "global.resolution.warning.dialog.title": "Mobile and low resolutions not supported"
		, "global.resolution.warning.dialog.textContent": "Atlascine is intended for desktop use with an appropriate resolution."
		, "Global Scale Factor": "Ring Thickness"
		, "global.scale.factor.tooltip": "Multiply the ring size by the given value"
		, "Global Time Offset": "Ring Animation Duration"
		, "global.time.offset.tooltip": "Duration in seconds for rings to scale in size"
		, "global.default.place.zoom.level.tooltip": "Default zoom level of map if animating to a place without specified zoomScale"
		, "widget.annotationEditor.contextMenu.timeLink": "Annotations"
		, "widget.annotationEditor.contextMenu.mapThemes": "Themes"
		, "widget.annotationEditor.contextMenu.settings": "Settings"
		, "widget.annotationEditor.mapThemeName": "Theme"
		, "widget.annotationEditor.mapThemeAssociatedTags": "Associated Tags"
		, "widget.annotationEditor.mapThemeAddNewTheme": "New Theme"
		, "widget.annotationEditor.settingsViewAllTimelinksNoAnnotationsText": "No annotations to display."
		, "gazetteer.dialog.title": "Search for a place name"
		, "mapAndControls.feature.addOrEdit.label": "Add Place"
		, "mapAndControls.feature.cancelEdit.label": "Cancel"
		, "gazetteer.dialog.subtitle.part1": "Search for a place in the "
		, "gazetteer.dialog.subtitle.urlText": "Geonames gazetteer"
		, "gazetteer.dialog.subtitle.part2": " to retrieve its coordinates."
		, "css.dialog.theme_selector.title": "Choose a style"
		, "css.theme.legacy": "Classic"
		, "css.theme.dark": "Dark"
		, "css.theme.light": "Light"
		, "donut.legend.timeline.logic.label": "Inclusive Selection"
		, "widget.annotationeditor.grouptag.invalid.name": "Themes cannot be blank."
		, "widget.annotationeditor.grouptag.invalid.colour": "A colour code is invalid."
		, "widget.annotationeditor.grouptag.missing.tags": "A theme must have at least one associated tag."
		, "widget.annotationeditor.grouptag.unmodified": "No changes were made."
	});
})(nunaliit2);
